name: Scheduled dependencies update
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-deps:
    name: Update Node dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: neverendingqs/gh-action-node-update-deps@v2
        with:
          bump-version: patch # defaults to not bumping the package version
          package-manager: bun # defaults to 'npm'
          github-token: ${{ secrets.MKLDEVOPS_GITHUB_TOKEN }} # defaults to the repo's `GITHUB_TOKEN`
          git-user-email: mkl.devops@gmail.com # defaults to '41898282+github-actions[bot]@users.noreply.github.com'
          git-user-name: MKL Devops [bot] # defaults to 'github-actions[bot]'
          pre-commit-script: bun run build # defaults to not running anything
          pull-request-labels: test # defaults to 'dependencies'
          target-version: minor # defaults to 'latest'
